perf: use precalculated offset pow size
kroma-network/tachyon pull request #103
Opened 2023-10-20 13:25 UTC by chokobole

# Description

1. This adds a comment about `barycentric weight`.
2. Use precalculated `offset_pow_size_` instead of powering repeatedly.

2023-10-21 05:56 UTC, Insun35 approved these changes
LGTM

2023-10-23 11:09 UTC, TomTaehoonKim requested changes

2023-10-23 11:09 UTC, TomTaehoonKim commented on tachyon/math/polynomials/univariate/univariate_evaluation_domain.h
> +  //          = 1 / (hᵐ⁻¹ * (1 - g¹) * (1 - g²) * .... * (1 - g^((m / 2) - 2)) * (1 - g^((m / 2) - 1)) * (1 + 1) * ... * (1 + g¹) * (1 + g²) * ... * (1 + g^((m / 2) - 2)) * (1 + g^((m / 2) - 1)))
```suggestion
  //          = 1 / (hᵐ⁻¹ * (1 - g¹) * (1 - g²) * .... * (1 - g^((m / 2) - 2)) * (1 - g^((m / 2) - 1)) * (1 + 1) * ... * (1 + g¹) * (1 + g²) * ... * (1 + g^((m / 2) - 2)) * (1 + g^((m / 2) - 1))) <- g^(m/2) = -1
```
How about adding this reason for the derivation?

2023-10-23 11:16 UTC, TomTaehoonKim approved these changes
LGTM

2023-10-23 11:33 UTC, merged