feat: implement halo2 common primitives
kroma-network/tachyon pull request #106
Opened 2023-10-23 06:03 UTC by chokobole

# Description

This PR adds common structures that used by `halo2-common` to `main`.

2023-10-23 07:49 UTC, dongchangYoo approved these changes
LGTM

2023-10-24 05:54 UTC, TomTaehoonKim commented
@chokobole Could you fix typo in the commit description in [1b140f1](https://github.com/kroma-network/tachyon/pull/106/commits/1b140f10a6e16ecd01af6fb9236501ed3381a2fc)? There is an unnecessary "i" in i[VirtualCell].

2023-10-24 06:15 UTC, chokobole commented
@TomTaehoonKim I fixed it.

> @chokobole Could you fix typo in the commit description in [1b140f1](https://github.com/kroma-network/tachyon/pull/106/commits/1b140f10a6e16ecd01af6fb9236501ed3381a2fc)? There is an unnecessary "i" in i[VirtualCell].

2023-10-24 07:01 UTC, TomTaehoonKim requested changes

2023-10-24 07:04 UTC, chokobole commented
Sorry for ugly rebase..

2023-10-24 07:33 UTC, chokobole commented on tachyon/zk/plonk/error.h
> +  // |k| is too small for the given circuit.
Oh it comes from rust comment and it looks like below.

```rust
    /// `k` is too small for the given circuit.
    NotEnoughRowsAvailable {
        /// The current value of `k` being used.
        current_k: u32,
    },
```

In this case it should be something like "The degree is too small for the given circuit."

2023-10-24 08:19 UTC, TomTaehoonKim commented on tachyon/zk/plonk/circuit/assignment.h
> +  // Not intended for downstream consumption; use |Layouter::AssignRegion()|
Do you know where |Layouter::AssignRegion()| is coming from? I can't find it from both tachyon and halo2 implementation.

2023-10-24 08:20 UTC, TomTaehoonKim commented on tachyon/zk/plonk/circuit/assignment.h
> +  // Not intended for downstream consumption; use |Layouter::namespace()|
Do you know where |Layouter::namespace()| is coming from? I can't find it from both tachyon and halo2 implementation.

2023-10-24 08:37 UTC, TomTaehoonKim commented on tachyon/zk/plonk/circuit/table_column.h
> +// A lookup table can be loaded into this column via |Layouter::AssignTable()].
Do you know where |Layouter::AssignRegion()| is coming from?

2023-10-24 10:25 UTC, chokobole commented on tachyon/zk/plonk/circuit/column_data.h
> +  size_t index = 0;
Make getter

2023-10-24 10:25 UTC, chokobole commented on tachyon/zk/plonk/lookup/lookup_argument.h
> +        });
Use `max_element()`

2023-10-24 10:25 UTC, chokobole commented on tachyon/zk/plonk/constraint_system.h
> +    degree = std::cmp::max(degree, ComputeGateRequiredDegree());
```suggestion
    degree = std::max(degree, ComputeGateRequiredDegree());
```

2023-10-24 13:02 UTC, chokobole commented on tachyon/zk/plonk/constraint_system.h
> +  void CreateGate(const std::string_view& name, ConstrainCallback constrain) {
I did it on purpose. for example, `annotate`.

2023-10-24 14:37 UTC, TomTaehoonKim approved these changes
LGTM! Great work!

2023-10-25 00:01 UTC, Insun35 approved these changes
LGTM

2023-10-25 00:43 UTC, merged