feat/implement open lookup evaluated
kroma-network/tachyon pull request #160
Opened 2023-11-07 11:19 UTC by lightscale-luke

* implement `Create()` on `ProverQuery` and `VerifierQuery`
* implement `Open()` on `LookupEvaluated`

2023-11-08 04:36 UTC, chokobole commented
Please change "build(zk): tidy up bazel build" to "refac(zk): tidy up headers"

2023-11-08 04:39 UTC, chokobole commented
Please include 6dd577c4675d6f08dcd5bb1139f94653c08f242c in "feat(zk): revert using ref_aliases.h" for reference.

2023-11-08 04:42 UTC, chokobole requested changes

2023-11-08 04:42 UTC, chokobole commented on tachyon/zk/base/prover_query_unittest.cc
> +  EXPECT_EQ(prover_query.poly()->blind(), blinded_poly_.blind());
```suggestion
  EXPECT_EQ(prover_query.poly(), blinded_poly_);
```

2023-11-08 04:42 UTC, chokobole commented on tachyon/zk/base/verifier_query_unittest.cc
I don't think this kind of unittests are worth doing it.

2023-11-08 04:42 UTC, chokobole commented on tachyon/zk/base/prover_query_unittest.cc
I don't think this kind of unittests are worth doing it.

2023-11-08 04:49 UTC, lightscale-luke commented on tachyon/zk/base/prover_query_unittest.cc
> +  EXPECT_EQ(prover_query.poly()->blind(), blinded_poly_.blind());
unit test deleted

2023-11-08 04:49 UTC, lightscale-luke commented on tachyon/zk/base/prover_query_unittest.cc
ok!. i will delete the unit tests

2023-11-08 04:49 UTC, lightscale-luke commented on tachyon/zk/base/verifier_query_unittest.cc
ok!. i will delete the unit tests

2023-11-08 05:24 UTC, TomTaehoonKim commented on tachyon/zk/plonk/lookup/lookup_evaluated.h
> +  template <typename ProverTy>
```suggestion
  template <typename ProverTy, typename PCSTy = ProverTy::PCSTy>
```

2023-11-08 05:27 UTC, TomTaehoonKim approved these changes
LGTM

2023-11-08 05:32 UTC, chokobole approved these changes
LGTM

2023-11-09 02:07 UTC, Insun35 approved these changes
LGTM

2023-11-09 02:11 UTC, Insun35 reviewed
Btw, the CI has failed. Please check.

2023-11-09 05:43 UTC, merged