feat(zk): integrate lookup transition metheds
kroma-network/tachyon pull request #178
Opened 2023-11-29 14:30 UTC by dongchangYoo

In this PR, the lookup state transition methods were integrated into the `LookupRunner`, allowing state transitions to be monitored from a single implementation.

[FYI] `Lookup arguments proof` has intermediate 4 states in proving process.
- `LookupArgument`
- `LookupPermuted`
- `LookupCommitted`
- `LookupEvaluated`
- finally, `ProverQuery` for lookup.

2023-11-30 05:53 UTC, chokobole requested changes

2023-11-30 07:07 UTC, chokobole approved these changes
LGTM

2023-11-30 08:25 UTC, Insun35 approved these changes
LGTM

2023-12-01 01:33 UTC, chokobole commented on tachyon/zk/plonk/lookup/lookup_argument_runner_impl.h
> +    Prover<PCSTy>* prover, LookupCommitted<Poly> committed, const F& x) {
Oh actually this should be opposite since all these data members are moved to create another data!

2023-12-01 01:36 UTC, chokobole commented on tachyon/zk/plonk/lookup/lookup_argument_runner_impl.h
> +    Prover<PCSTy>* prover, const LookupPermuted<Poly, Evals>& permuted,
```suggestion
    Prover<PCSTy>* prover, LookupPermuted<Poly, Evals>&& permuted,
```

2023-12-01 01:39 UTC, chokobole commented on tachyon/zk/plonk/lookup/lookup_argument_runner_impl.h
> +                               std::move(permuted.permuted_table_poly()),
```suggestion
  return LookupCommitted<Poly>(std::move(permuted).permuted_input_poly()),
                               std::move(permuted).permuted_table_poly()),
```

With this modificaiton!

```c++
  BlindedPolynomial<Poly>&& permuted_input_poly() && {
    return std::move(permuted_input_poly_);
  }
```

2023-12-01 05:34 UTC, dongchangYoo commented on tachyon/zk/plonk/lookup/permute_expression_pair.h
> +  size_t blinding_factors = prover->blinder().blinding_factors();
This is not in scope of the PR any more.

2023-12-01 05:34 UTC, dongchangYoo commented on tachyon/zk/plonk/lookup/lookup_evaluated.h
> +    F x_next = Rotation::Next().RotateOmega(prover->domain(), x);
This is not in scope of the PR any more.

2023-12-01 06:37 UTC, chokobole requested changes

2023-12-01 06:37 UTC, chokobole commented on tachyon/zk/plonk/lookup/lookup_argument_runner_impl.h
> +    LookupPermuted<Poly, Evals>& permuted, const F& beta, const F& gamma) {
```suggestion
    const LookupPermuted<Poly, Evals>& permuted, const F& beta, const F& gamma) {
```

2023-12-01 06:37 UTC, chokobole commented on tachyon/zk/plonk/lookup/lookup_argument_runner.h
> +      Prover<PCSTy, ExtendedDomain>* prover, LookupArgument<F>&& argument,
```suggestion
      Prover<PCSTy, ExtendedDomain>* prover, const LookupArgument<F>& argument,
```

2023-12-01 07:22 UTC, TomTaehoonKim approved these changes
LGTM

2023-12-01 09:20 UTC, merged