feat(zk): create halo2 proving key by deser
kroma-network/tachyon pull request #243
Opened 2024-01-22 06:13 UTC by chokobole

# Description

This PR creates Halo2 Proving Key by deserializing the byte array which is serialized from https://github.com/kroma-network/halo2/commit/746e4ac62ea39e8fec9f711a6b5a359dfa596818.

2024-01-22 06:55 UTC, TomTaehoonKim commented
@chokobole Is ? in [d7623d5](https://github.com/kroma-network/tachyon/pull/243/commits/d7623d57849fb272878b9dc255219390fe23b03c) typo?

2024-01-22 07:00 UTC, chokobole commented
> @chokobole Is ? in [d7623d5](https://github.com/kroma-network/tachyon/pull/243/commits/d7623d57849fb272878b9dc255219390fe23b03c) typo?

I meant regular expressions. If it doesn't deliever clear message, then i can change the commit message!

2024-01-22 07:01 UTC, TomTaehoonKim commented
@chokobole Nah, I think it's fine

2024-01-22 13:12 UTC, TomTaehoonKim requested changes

2024-01-22 13:12 UTC, TomTaehoonKim commented on vendors/halo2/src/lib.rs
> +mod xor_shift_rng;
:+1:

2024-01-22 22:47 UTC, TomTaehoonKim approved these changes
LGTM

2024-01-23 01:45 UTC, Insun35 approved these changes
LGTM

2024-01-23 01:53 UTC, ashjeong commented
https://github.com/kroma-network/tachyon/pull/243/commits/0f6f531686a202fa96a6a12e68724a2f17e3284a
Rather than a "refac" commit I believe this should be a "style" commit as per [Angular Convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines) and [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/); however, we do not currently use "style" type commits as per Kroma's [.github](https://github.com/kroma-network/.github/blob/main/CONTRIBUTING.md). Perhaps we should take this into account and discuss further later on.

2024-01-23 09:22 UTC, dongchangYoo approved these changes
LGTM

2024-01-23 09:22 UTC, merged