docs: add commit type
kroma-network/tachyon pull request #246
Opened 2024-01-23 05:26 UTC by Insun35

- Fix typo in folder name: developement -> development
- Add Commit Message Format in `convention.md`

2024-01-23 06:33 UTC, chokobole approved these changes
LGTM

2024-01-23 08:05 UTC, TomTaehoonKim approved these changes
LGTM

2024-01-24 02:04 UTC, ashjeong requested changes

2024-01-24 02:13 UTC, ashjeong commented on docs/development/convention.md
> +There are some cases where it is ambiguous to classify the commit type. Here are the cases we follow:
Actually, I think that including the first sentence is useful in providing context for the section

The second sentence can be worded as you wish possibly as such (or mix-matched):
"Here are further clarifications on how to determine the proper commit type given previous cases we have come across."
"Here are further clarifications we follow to determine the proper commit type given previous cases encountered."
"Given previous ambiguous cases, we have adopted the following additional guidelines:"

2024-01-24 06:54 UTC, ashjeong approved these changes
LGTM

2024-01-24 07:14 UTC, dongchangYoo approved these changes
LGTM

2024-01-24 07:17 UTC, merged