fix: fix bug on create proof
kroma-network/tachyon pull request #247
Opened 2024-01-24 09:11 UTC by dongchangYoo

In this PR, the missing reviews of [PR#238](https://github.com/kroma-network/tachyon/pull/238) are applied. (related to `Argument::GenerateInstancePolys()`)
- The bug where the wrong method was called.
- has been refactored for removing redundant code.
- The Instance type required for calling `CreateProof()` has been changed.

2024-01-24 09:19 UTC, chokobole commented on tachyon/zk/plonk/halo2/argument.h
> +    });
Please use for-loop instead

2024-01-24 09:19 UTC, chokobole commented on tachyon/zk/plonk/halo2/argument.h
> +        if constexpr (PCS::kQueryInstance && !PCS::kSupportsBatchMode) {
```suggestion
        } else if constexpr (PCS::kQueryInstance && !PCS::kSupportsBatchMode) {
```

2024-01-24 09:19 UTC, chokobole commented on tachyon/zk/plonk/halo2/argument.h
> +        if constexpr (!PCS::kQueryInstance) {
```suggestion
        } else {
```

2024-01-25 01:44 UTC, chokobole approved these changes
LGTM

2024-01-25 02:05 UTC, TomTaehoonKim requested changes

2024-01-25 02:05 UTC, TomTaehoonKim commented on tachyon/zk/plonk/halo2/argument.h
> +        instance_column.evaluations().resize(n, F::Zero());
```suggestion
        instance_column.evaluations().resize(n);
```
+ shouldn't this change go with the previous commit?

2024-01-25 06:21 UTC, Insun35 approved these changes
LGTM

2024-01-25 06:54 UTC, TomTaehoonKim approved these changes
LGTM

2024-01-25 06:54 UTC, merged