test(zk): add GraphEvaluator unit test
kroma-network/tachyon pull request #256
Opened 2024-01-28 14:36 UTC by Insun35

Add Negated, Sum, Product, and Scaled test in GraphEvaluator unit test

2024-01-29 06:07 UTC, chokobole commented on tachyon/zk/plonk/vanishing/graph_evaluator_unittest.cc
> +      expected_intermediates++;
```suggestion
      ++expected_intermediates;
```

2024-01-29 06:07 UTC, chokobole commented on tachyon/zk/plonk/vanishing/graph_evaluator_unittest.cc
> +  int expected_intermediates = 0;
```suggestion
  size_t expected_intermediate_index = 0;
```

2024-01-29 07:45 UTC, Insun35 commented on tachyon/zk/plonk/vanishing/graph_evaluator_unittest.cc
> +  void SetUp() override {
I just added `GenerateTestColumnInfos()` for the test case, because it is not used in every test.

2024-01-29 10:07 UTC, chokobole approved these changes
LGTM

2024-01-30 01:58 UTC, dongchangYoo approved these changes
LGTM

2024-01-30 05:14 UTC, TomTaehoonKim requested changes

2024-01-30 05:14 UTC, TomTaehoonKim commented on tachyon/zk/plonk/vanishing/graph_evaluator_unittest.cc
> +  //      intermediate = {test_column₀, Negate(test_column₀)}
Can you fix all intermediate/intermediates to calculations_? Maybe renaming `calculations_` in `GraphEvaluator` to `intermediates_` might be another great choice as well.

2024-01-30 06:10 UTC, TomTaehoonKim approved these changes
LGTM

2024-01-30 06:10 UTC, merged