refac: minimize using template types
kroma-network/tachyon pull request #262
Opened 2024-01-30 05:00 UTC by chokobole

# Description

This PR minimizes using template types. The problem arises when creating c binding APIs for `ProvingKey`. Since tme template type of `ProvingKey` is `PCS`, the corresponding APIs for creating this structure is something like `tachyon_bn254_shplonk_plonk_proving_key_create()`. But when seeing the members in it, it doesn't actually depend on `PCS`. So the team decided as follows.

**Other than `Entity<PCS>`, DO NOT USE template `PCS`**

2024-01-30 09:42 UTC, TomTaehoonKim requested changes
LGTM

2024-01-30 10:08 UTC, chokobole commented on tachyon/zk/base/blinder_unittest.cc
> +    }
Actually this is changed at https://github.com/kroma-network/tachyon/pull/253/files#diff-f2413a4de51629169154be6d4a9fbb49abdce0a5f12d6eed5355cc196708fbb7R38-R39. 

Do you think it's more readable? I think it's styling issue and it is different from people to people, and I should've not modified it there. :(

2024-01-30 10:31 UTC, TomTaehoonKim commented on tachyon/zk/base/blinder_unittest.cc
> +    }
Oh yeah, I think it's just preference issue. Then could you just fix like below?
```suggestion
    RowIndex blinding_rows = kBlindingFactors;
    if (include_last_row) ++blinding_rows;
```

2024-01-30 11:17 UTC, chokobole commented on tachyon/zk/base/blinder_unittest.cc
> +    }
You want to make it look similar to the `Blind()`, right? Okay

2024-01-30 13:00 UTC, TomTaehoonKim approved these changes
LGTM

2024-01-30 14:06 UTC, Insun35 approved these changes
LGTM

2024-01-31 06:16 UTC, dongchangYoo approved these changes
LGTM

2024-01-31 06:23 UTC, merged