feat(math): implement fixed base msm
kroma-network/tachyon pull request #276
Opened 2024-02-02 14:25 UTC by chokobole

# Description

This PR adds `FixedBaseMSM` which is used by groth16. Existing `MSMXXX` is named to `VariableBaseMSMXXX` to differentiate it from `FixedBaseMSM`.

2024-02-05 02:06 UTC, TomTaehoonKim requested changes

2024-02-05 02:06 UTC, TomTaehoonKim commented on tachyon/math/elliptic_curves/msm/fixed_base_msm.h
> +// MSM(Multi-Scalar Multiplication): s₀ * g₀ + s₁ * g₁ + ... + sₙ * gₙ
```suggestion
// MSM(Multi-Scalar Multiplication): s₀ * g + s₁ * g + ... + sₙ * g
```

2024-02-05 04:18 UTC, ashjeong approved these changes
LGTM

2024-02-05 05:36 UTC, TomTaehoonKim approved these changes
LGTM

2024-02-05 05:40 UTC, Insun35 approved these changes
LGTM

2024-02-06 01:02 UTC, dongchangYoo approved these changes
LGTM

2024-02-06 01:17 UTC, merged