fix: correct parallel computation
kroma-network/tachyon pull request #281
Opened 2024-02-06 01:17 UTC by chokobole

# Description

This PR fixes the bug related to openmp.

2024-02-06 01:37 UTC, ashjeong approved these changes
LGTM

2024-02-06 03:56 UTC, Insun35 approved these changes
LGTM

2024-02-06 03:59 UTC, dongchangYoo approved these changes
LGTM

2024-02-06 04:36 UTC, TomTaehoonKim requested changes

2024-02-06 04:36 UTC, TomTaehoonKim commented on tachyon/math/polynomials/univariate/lagrange_interpolation.h
> +    //      = ∑ᵢ (P(Xᵢ) * Dᵢ * (cₙ₋₁Xⁿ⁻¹ + cₙ₋₂Xⁿ⁻² + ... + c₁X¹ + c₀X⁰))
```suggestion
    // P(X) = ∑ᵢ(P(Xᵢ) * Dᵢ * Nᵢ(X))
    //      = ∑ᵢ(P(Xᵢ) * Dᵢ * (cₙ₋₁Xⁿ⁻¹ + cₙ₋₂Xⁿ⁻² + ... + c₁X¹ + c₀X⁰))
```

2024-02-06 04:36 UTC, TomTaehoonKim commented on tachyon/math/polynomials/univariate/lagrange_interpolation.h
> +        denom *= (points[i] - points[j]);
It's same as below right?
```c++
        if (i == j) {
          denom *= (points[i] - points[j]);
        }
```

2024-02-06 04:41 UTC, chokobole commented on tachyon/math/polynomials/univariate/lagrange_interpolation.h
> +        denom *= (points[i] - points[j]);
Yeap!

2024-02-06 04:42 UTC, TomTaehoonKim approved these changes
LGTM

2024-02-06 05:54 UTC, merged

2024-02-20 23:27 UTC, sengulatik66 commented
LGTM