feat: add transcript c apis for kroma prover
kroma-network/tachyon pull request #300
Opened 2024-02-16 04:47 UTC by chokobole

# Description

To run [kroma-prover v0.1.4](https://github.com/kroma-network/kroma-prover/tree/v0.1.4), we need to support more transcripts, `Poseidon` and `Sha256`. This PR creates c APIs for them.

2024-02-16 08:18 UTC, ashjeong reviewed
In previous commits like 5e12d2143c238789d6f3d8807b07e816329483e7 , ec46ffc000cf0432044556b5d97476f0a849c8a5 , and ced3d58bc0bf30609e757e489e50c3400d594b57 you include the copyable unit test in the commit about adding copyable, but you don’t do so for f73a8d5acac3ecd016c49d6e1a803508dddb6196 . Can you change this commit to be part of https://github.com/kroma-network/tachyon/pull/300/commits/ced3d58bc0bf30609e757e489e50c3400d594b57 or separate the other commits as well?

2024-02-16 08:18 UTC, ashjeong commented on tachyon/c/zk/plonk/halo2/bn254_transcript.h
> +// If the type of the transcript is other than poseidon, it terminates the
```suggestion
// If the type of the transcript is not poseidon, it terminates the
```

2024-02-19 01:04 UTC, chokobole commented
> In previous commits like [5e12d21](https://github.com/kroma-network/tachyon/commit/5e12d2143c238789d6f3d8807b07e816329483e7) , [ec46ffc](https://github.com/kroma-network/tachyon/commit/ec46ffc000cf0432044556b5d97476f0a849c8a5) , and [ced3d58](https://github.com/kroma-network/tachyon/commit/ced3d58bc0bf30609e757e489e50c3400d594b57) you include the copyable unit test in the commit about adding copyable, but you don’t do so for [f73a8d5](https://github.com/kroma-network/tachyon/commit/f73a8d5acac3ecd016c49d6e1a803508dddb6196) . Can you change this commit to be part of [ced3d58](https://github.com/kroma-network/tachyon/commit/ced3d58bc0bf30609e757e489e50c3400d594b57) or separate the other commits as well?


I intentionally structured it this way because to add a Copyable unittest, I needed to implement a commit that adds the equality operator first.

1. Equality operator
2. Copyable
3. Copyable test

However, upon reflection, I realize I can combine the implementation and test commits into one by changing the order as follows:

1. Equality operator
2. Copyable

2024-02-19 01:52 UTC, ashjeong approved these changes
LGTM

2024-02-19 04:35 UTC, TomTaehoonKim requested changes

2024-02-19 04:35 UTC, TomTaehoonKim commented on tachyon/c/zk/plonk/halo2/bn254_transcript.cc
> +             math::bn254::Fr::BigIntTy::kByteNums);
```suggestion
             math::bn254::Fr::BigIntTy::kLimbNums);
```

2024-02-19 04:40 UTC, TomTaehoonKim approved these changes
LGTM

2024-02-19 08:15 UTC, Insun35 approved these changes
LGTM

2024-02-19 14:10 UTC, dongchangYoo approved these changes
LGTM

2024-02-19 14:10 UTC, merged