feat: apply c gwc api to rust bindings
kroma-network/tachyon pull request #305
Opened 2024-02-20 04:24 UTC by chokobole

# Description

This PR is a follow-up tasks after #296. 

- This fixes bugs w.r.t GWC prover.
- This adds rust bindings for GWC prover.

2024-02-20 07:49 UTC, TomTaehoonKim requested changes

2024-02-20 07:49 UTC, TomTaehoonKim commented on tachyon/c/zk/plonk/halo2/kzg_family_prover_impl.h
> +        bases.data(), std::min(bases.size(), scalars.size()));
```suggestion
    absl::Span<const AffinePoint> bases_span(
        bases.data(), std::min(bases.size(), scalars.size()));
```

2024-02-20 07:49 UTC, TomTaehoonKim commented on vendors/halo2/src/prover.rs
> +                        });
Is this change necessary?

2024-02-20 07:49 UTC, TomTaehoonKim commented on vendors/halo2/src/prover.rs
> +                    })?;
Is this change necessary?

2024-02-20 07:49 UTC, TomTaehoonKim commented on tachyon/zk/lookup/halo2/prover_impl.h
> +  // NOTE(chokobole): The ORDER IS IMPORTANT!!!
```suggestion
  // The ORDER IS IMPORTANT!!!
```
I thought we were removing NOTE(author) comments. https://github.com/kroma-network/tachyon/commit/98db4aa004b6202d9ca0660b74456f30f1dc2102

2024-02-20 07:49 UTC, TomTaehoonKim commented on tachyon/zk/lookup/halo2/prover_impl.h
> +  // NOTE(chokobole): The ORDER IS IMPORTANT!!!
```suggestion
  // The ORDER IS IMPORTANT!!!
```
I thought we were removing NOTE(author) comments. https://github.com/kroma-network/tachyon/commit/98db4aa004b6202d9ca0660b74456f30f1dc2102

2024-02-20 07:49 UTC, TomTaehoonKim commented on tachyon/zk/plonk/permutation/permutation_prover_impl.h
> +  // NOTE(chokobole): The ORDER IS IMPORTANT!!!
```suggestion
  // The ORDER IS IMPORTANT!!!
```
I thought we were removing NOTE(author) comments. https://github.com/kroma-network/tachyon/commit/98db4aa004b6202d9ca0660b74456f30f1dc2102

2024-02-20 07:49 UTC, TomTaehoonKim commented on tachyon/zk/plonk/permutation/permutation_prover_impl.h
> +  // NOTE(chokobole): The ORDER IS IMPORTANT!!!
```suggestion
  // The ORDER IS IMPORTANT!!!
```
I thought we were removing NOTE(author) comments. https://github.com/kroma-network/tachyon/commit/98db4aa004b6202d9ca0660b74456f30f1dc2102

2024-02-20 08:31 UTC, chokobole commented on vendors/halo2/src/prover.rs
> +                    })?;
Nice catch!

2024-02-20 08:33 UTC, chokobole commented on vendors/halo2/src/prover.rs
> +                        });
This is the error message without this.

```
error[E0308]: mismatched types
   --> vendors/halo2/src/prover.rs:80:43
    |
80  |                         poly.set_value(i, &values[i]);
    |                              ---------    ^^^^^^^^^^ expected struct `halo2curves::bn256::Fr`, found associated type
    |                              |
    |                              arguments to this function are incorrect
    |
    = note: expected reference `&halo2curves::bn256::Fr`
               found reference `&<Scheme as CommitmentScheme>::Scalar`
    = help: consider constraining the associated type `<Scheme as CommitmentScheme>::Scalar` to `halo2curves::bn256::Fr`
    = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html
note: associated function defined here
   --> vendors/halo2/src/bn254.rs:403:12
    |
403 |     pub fn set_value(&mut self, idx: usize, fr: &halo2curves::bn256::Fr) {
    |            ^^^^^^^^^                        ---------------------------

error: aborting due to previous error
```

2024-02-20 10:09 UTC, TomTaehoonKim approved these changes
LGTM

2024-02-20 13:31 UTC, Insun35 approved these changes
LGTM

2024-02-21 01:57 UTC, dongchangYoo approved these changes
LGTM

2024-02-21 05:36 UTC, ashjeong commented on vendors/halo2/src/bn254_gwc_prover.cc
> +  // fine.
```suggestion
  // NOTE(chokobole): Leading zero values may be removed at this point, so use
  // this function cautiously. Tachyon currently uses it safely.

2024-02-21 08:01 UTC, ashjeong approved these changes
LGTM :)

2024-02-21 08:55 UTC, merged