perf: optimize fft ifft
kroma-network/tachyon pull request #306
Opened 2024-02-20 06:41 UTC by dongchangYoo

In this PR, the FFT and IFFT was improved by removing redundant calculation.
1. `InOutHelper` and `OutInHelper` were modified so that `GetRootsOfUnity`
is no longer called upon their invocation. Instead, the domain is precomputed and stored at the time of creation.
3. The `CoeffToExtendedPart`, which was being called multiple times, was modified
    to stop creating the same coset domain repeatedly.
    Instead, the coset domain is now created by the caller and passed to the function.

2024-02-20 07:20 UTC, chokobole commented on tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
> +      idx += 1;
```suggestion
    while (gap < evals.evaluations_.size()) {
          ApplyButterfly<FFTOrder::kOutIn>(evals, roots_vec_[idx++], 1, gap);
          gap *= 2;
```

2024-02-20 07:20 UTC, chokobole commented on tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
> +      idx += 1;
In addition, is the `step` argument of `ApplyButterfly` always one?, then please remove the argument

2024-02-20 07:20 UTC, chokobole commented on tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc
> +  for (size_t coeffs = 2; coeffs < kNumCoeffs; ++coeffs) {
Why did you change these number?

2024-02-21 07:10 UTC, TomTaehoonKim requested changes

2024-02-21 07:10 UTC, TomTaehoonKim commented on tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
> +    // Assign every elements based biggest vectors.
```suggestion
    // Assign every elements based on biggest vectors.
```

2024-02-21 08:45 UTC, chokobole approved these changes
LGTM

2024-02-22 01:58 UTC, TomTaehoonKim approved these changes
LGTM

2024-02-22 05:07 UTC, Insun35 approved these changes
LGTM

2024-02-22 05:32 UTC, ashjeong approved these changes
I changed 2. of the description, plz change commit description accordingly.

2024-02-22 05:38 UTC, dongchangYoo commented on tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
> +        inv_roots_vec_[i][j] = inv_roots_vec_.front()[k];
The end condition of Inner for-loop is determined on demand (not static). So  `OPENMP_PARALLEL_NESTED_FOR` can not be applied here.

2024-02-22 07:38 UTC, ashjeong approved these changes
LGTM

2024-02-22 07:38 UTC, merged