fix(zk): fix bug on the PR #302
kroma-network/tachyon pull request #310
Opened 2024-02-20 11:56 UTC by dongchangYoo

In this PR, code changes that made code, which should not operate in parallel, to run in parallel was reverted.

2024-02-20 12:00 UTC, TomTaehoonKim commented
This PR should be merged after #305.

2024-02-20 12:03 UTC, TomTaehoonKim approved these changes
LGTM

2024-02-20 13:05 UTC, Insun35 approved these changes
LGTM

2024-02-20 13:53 UTC, chokobole requested changes

2024-02-20 13:53 UTC, chokobole commented on tachyon/zk/lookup/halo2/prover_impl.h
> +    openings.emplace_back(OPENING(grand_product_poly, x_next));
Could you change this to original? This will be included in https://github.com/kroma-network/tachyon/pull/305

2024-02-21 08:22 UTC, ashjeong commented
I changed the description - please reflect the changed wording in the commit description as well~
The commit name would be more aptly named as "fix bug in PR#302"

2024-02-21 10:42 UTC, chokobole approved these changes
LGTM

2024-02-22 01:59 UTC, merged