feat: support circom
kroma-network/tachyon pull request #327
Opened 2024-02-23 16:40 UTC by chokobole

# Description

This PR enables circom frontend support.

2024-02-26 06:06 UTC, ashjeong commented on vendors/circom/circomlib/r1cs/r1cs.h
> +  // Total Number of wires including ONE signal (Index 0).
```suggestion
  // Total number of wires including ONE signal (Index 0).
  ```
  & all others

2024-02-26 06:06 UTC, ashjeong commented on vendors/circom/circomlib/r1cs/r1cs_parser.h
> +  // Return nullptr if the parser is failed to parse.
```suggestion
  // Return nullptr if the parser fails to parse.

2024-02-26 06:53 UTC, ashjeong approved these changes
LGTM

2024-02-26 07:50 UTC, Insun35 requested changes

2024-02-26 07:50 UTC, Insun35 commented on vendors/circom/circomlib/r1cs/r1cs.h
> +  // Total number of wires public output wires. They should be starting at
Please remove duplicate words.
```suggestion
  // Total number of public output wires. They should be starting at
```

2024-02-26 07:50 UTC, Insun35 commented on vendors/circom/circomlib/r1cs/r1cs.h
> +  // Total number of wires public input wires. They should be starting just
Please remove duplicate words.
```suggestion
  // Total number of public input wires. They should be starting just
```

2024-02-26 07:50 UTC, Insun35 commented on vendors/circom/circomlib/r1cs/r1cs.h
> +  // Total number of wires private input wires. They should be starting just
Please remove duplicate words.
```suggestion
  // Total number of private input wires. They should be starting just
```

2024-02-26 07:57 UTC, Insun35 approved these changes
LGTM

2024-02-27 00:45 UTC, dongchangYoo approved these changes
LGTM

2024-02-27 00:45 UTC, merged