feat: make generator use template files
kroma-network/tachyon pull request #347
Opened 2024-03-12 08:42 UTC by dongchangYoo

Existing `code-generators` create files line by line as strings, making it difficult to see at a glance what file will be generated. This PR solves the problem by having the `code-generator` substitute template files to create each file.

2024-03-12 09:27 UTC, chokobole commented on tachyon/math/elliptic_curves/bn/generator/curve.h.tpl
> +  // NOTE(chokobole): Make them constexpr."
```suggestion
  // NOTE(chokobole): Make them constexpr.
```

2024-03-12 09:27 UTC, chokobole commented on tachyon/math/elliptic_curves/bn/generator/curve.h.tpl
> +#include "tachyon/math/elliptic_curves/pairing/twist_type.h"
```suggestion
#include "tachyon/math/elliptic_curves/bn/bn_curve.h"
#include "tachyon/math/elliptic_curves/pairing/twist_type.h"
#include "%{fq12_hdr}"
#include "%{g1_hdr}"
#include "%{g2_hdr}"
```

2024-03-12 09:27 UTC, chokobole commented on tachyon/math/elliptic_curves/short_weierstrass/generator/generator.cc
> +  return ss.str();
```suggestion
  if (a_value == 0) return "    return BaseField::Zero();";
  if (mul_by_a_fast) {
    std::stringstream ss;
    ss << "    return ";
    ss << math::GenerateFastMultiplication(a_value) << ";";
    return ss.str();
  }
  return "    return kA * v;";
```

2024-03-12 12:44 UTC, chokobole commented on tachyon/math/finite_fields/generator/prime_field_generator/prime_field_generator.cc
> +#include <map>
Please remove this!

2024-03-12 12:44 UTC, chokobole commented on tachyon/math/finite_fields/generator/ext_prime_field_generator/ext_prime_field_generator.cc
> +#include <map>
Please remove this

2024-03-12 12:44 UTC, chokobole commented on tachyon/math/elliptic_curves/bn/generator/generator.cc
> +#include <map>
Please remove this

2024-03-12 12:46 UTC, chokobole commented on tachyon/math/elliptic_curves/bls12/generator/curve.h.tpl
> +#include "tachyon/math/elliptic_curves/pairing/twist_type.h"
```suggestion
#include "tachyon/math/elliptic_curves/bls12/bls12_curve.h"
#include "tachyon/math/elliptic_curves/pairing/twist_type.h"
#include "%{fq12_hdr}"
#include "%{g1_hdr}"
#include "%{g2_hdr}"
```

2024-03-13 04:47 UTC, chokobole approved these changes
LGTM

2024-03-13 04:50 UTC, Insun35 approved these changes
LGTM

2024-03-13 06:26 UTC, TomTaehoonKim approved these changes
LGTM

2024-03-13 07:16 UTC, ashjeong requested changes
Note - I also changed the PR's title.

2024-03-13 07:16 UTC, ashjeong commented on tachyon/build/cc_writer.h
> +  // Remove the each first line that equals to |start_line| and |end_line| if
```suggestion
  // Remove each first line that equals to |start_line| and |end_line| if

2024-03-13 07:32 UTC, ashjeong approved these changes
LGTM

2024-03-13 10:28 UTC, merged