perf: avoid in place operator where ineffective
kroma-network/tachyon pull request #372
Opened 2024-04-02 14:41 UTC by chokobole

# Description

This commit enhances performance by utilizing the `c = a op b` style instead of `c = a; c inplace-op b`. While the former style is nearly as performant as the latter when `a` is movable, it becomes inefficient when operating on prime fields or points on elliptic curves that are not able to be moved. This change ensures better performance and readability, reducing 2 lines to 1. Note that irrelevant changes may occur due to this adjustment.

2024-04-03 04:30 UTC, dongchangYoo approved these changes
LGTM

2024-04-03 06:07 UTC, Insun35 approved these changes
LGTM

2024-04-03 07:18 UTC, TomTaehoonKim approved these changes
LGTM

2024-04-04 06:47 UTC, ashjeong requested changes
I tried to only include small fixes/ changes related to the commit, yet there appears to be a lot of redundant or unneeded variables or calculations. Perhaps a separate pr may be needed to fix these.

2024-04-04 06:47 UTC, ashjeong commented on tachyon/math/elliptic_curves/short_weierstrass/projective_point_impl.h
>      w += Curve::Config::MulByA(zz);
```suggestion
  BaseField w = xx.Double();
  w += xx;
  if constexpr (!Curve::Config::kAIsZero) {
    w += Curve::Config::MulByA(std::move(zz));

2024-04-04 06:47 UTC, ashjeong commented on tachyon/math/finite_fields/fp12.h
> +    this->c0_ = Config::MulByNonResidue(b) + a;
I don't think this should be changed:
its equal to the case 
```c++
z = b * c + a
```
which should be treated as such:
```c++
z = b * c;
z += a;
```

 REF[0] for future similar scenarios

2024-04-04 06:47 UTC, ashjeong commented on tachyon/math/finite_fields/fp12.h
> +    this->c0_ = Config::MulByNonResidue(b) + a;
refer to REF[0]

2024-04-04 07:44 UTC, chokobole commented on tachyon/math/finite_fields/fp6.h
> +    this->c0_ = Config::MulByNonResidue(t0);
We can't do that, `c0` is used to compute `c1`, and `c1` is used to compute `c2` so we need to do in this order.

2024-04-04 07:48 UTC, chokobole commented on tachyon/math/elliptic_curves/short_weierstrass/projective_point_impl.h
>      w += Curve::Config::MulByA(zz);
Actually `MulByA()` takes const reference as an argument!

2024-04-04 07:52 UTC, ashjeong commented on tachyon/math/finite_fields/fp6.h
> +    this->c0_ = Config::MulByNonResidue(t0);
oops yea didn't catch that

2024-04-04 23:01 UTC, merged