feat(math): add range check to string conversion methods
kroma-network/tachyon pull request #389
Opened 2024-04-13 08:49 UTC by chokobole

# Description

This PR adds features as follows:

1. helpful error message when failed to parse `BigInt<N>`.
2. add range check to `PrimeFieldXXX::From(Dec|Hex)String`.

2024-04-15 01:54 UTC, dongchangYoo approved these changes
LGTM

2024-04-15 07:09 UTC, ashjeong requested changes
https://github.com/kroma-network/tachyon/pull/389/commits/7d6e8c1b49d5806f508b2e7cc6060d59262c90dd
chore(math): add helpful error message when **failed** to parse BigInt<N>
->
chore(math): add helpful error message when **failing** to parse BigInt<N>

2024-04-15 07:09 UTC, ashjeong commented on tachyon/math/finite_fields/generator/prime_field_generator/prime_field_x86.h.tpl
> +      LOG(ERROR) << "value(" << str << ") is grater than modulus";
Fix all instances!
```suggestion
      LOG(ERROR) << "value(" << str << ") is greater than modulus";

2024-04-15 08:33 UTC, Insun35 approved these changes
LGTM

2024-04-15 12:43 UTC, TomTaehoonKim commented on tachyon/math/finite_fields/generator/prime_field_generator/prime_field_x86.h.tpl
> +      LOG(ERROR) << "value(" << str << ") is grater than modulus";
```suggestion
      LOG(ERROR) << "value(" << str << ") is greater than or equal to modulus";
```

2024-04-15 12:43 UTC, TomTaehoonKim commented on tachyon/math/finite_fields/generator/prime_field_generator/prime_field_x86.h.tpl
> +      LOG(ERROR) << "value(" << str << ") is grater than modulus";
```suggestion
      LOG(ERROR) << "value(" << str << ") is greater than or equal to modulus";
```

2024-04-16 09:06 UTC, ashjeong approved these changes
LGTM

2024-04-16 10:12 UTC, TomTaehoonKim approved these changes
LGTM

2024-04-16 11:52 UTC, merged