refac(math): rename filenames
kroma-network/tachyon pull request #399
Opened 2024-04-22 12:12 UTC by chokobole

# Description

This refactor renames the following files:

- `prime_field_generic.h` to `prime_field_fallback.h`: This file is enabled when there's no optimized assembly code for the building architecture, hence the name fallback.
- small_prime_field_generic.h to small_prime_field.h: This file is enabled for all prime fields whose modulus is less than 32 bits,
 hence the simplified name.

2024-04-23 01:53 UTC, ashjeong requested changes

2024-04-23 01:53 UTC, ashjeong commented on tachyon/math/finite_fields/small_prime_field_generic.h
> +                 << ") is is greater than or equal to modulus";
```suggestion
                 << ") is greater than or equal to modulus";

2024-04-23 01:53 UTC, ashjeong commented on tachyon/math/finite_fields/small_prime_field_generic.h
> +                 << ") is is greater than or equal to modulus";
```suggestion
                 << ") is greater than or equal to modulus";

2024-04-24 02:09 UTC, Insun35 approved these changes
LGTM

2024-04-24 04:44 UTC, ashjeong approved these changes
LGTM

2024-04-24 13:01 UTC, dongchangYoo approved these changes
LGTM

2024-04-25 07:05 UTC, TomTaehoonKim approved these changes
LGTM

2024-04-25 07:22 UTC, merged