build: support building with clang on ubuntu
kroma-network/tachyon pull request #414
Opened 2024-05-08 09:43 UTC by chokobole

# Description

This PR enables buliding tachyon with clang on ubuntu 22.04

2024-05-08 10:18 UTC, chokobole commented
Since a lint error has occurred in `tachyon/base/threading/platform_thread_linux.cc`, which belongs to Chromium, to keep the differences minimal, I kindly request that you ignore this :pray:

2024-05-10 06:28 UTC, dongchangYoo approved these changes
LGTM

2024-05-13 08:14 UTC, ashjeong requested changes
https://github.com/kroma-network/tachyon/pull/414/commits/b30a8f6a3dff6d11989e7fa96fce01c8b958bb5a
Please change the commit title to a `constexpr` (with `) to match the commit before

https://github.com/kroma-network/tachyon/pull/414/commits/bd15530fbd82deccfc327a1e32ac05afaf637331
Please change the commit message to this:
When linking rust tests with clang, clang **detects and tries to use the system** installed intel openmp **even when compiling** without the option `--//:has_intel_openmp`,.

2024-05-13 08:14 UTC, ashjeong commented on docs/how_to_use/how_to_build.md
> +you'll need clang++ version 15 or higher. By default, Ubuntu 22.04 installs `clang-14` via `apt install clang`,
```suggestion
you'll need clang++ at version 15 or higher. By default, Ubuntu 22.04 installs `clang-14` via `apt install clang`,

2024-05-13 08:14 UTC, ashjeong commented on docs/how_to_use/how_to_build.md
> +```
```suggestion
Next, update `CC` and `CXX` to point to the newly installed `clang-15` and `clang++-15`:

```shell
export CC=/usr/bin/clang-15
export CXX=/usr/bin/clang++-15
__ <- @ashjeong: ignore this - formatting is off

Make sure `CC` and `CXX` are properly updated to `clang-15` and `clang++-15`.
```

2024-05-13 08:14 UTC, ashjeong commented on docs/how_to_use/how_to_build.md
> +First, install clang-15 and the appropriate OpenMP libraries:
```suggestion
First, install `clang-15` and the appropriate OpenMP libraries:

2024-05-13 08:42 UTC, chokobole commented on tachyon/base/threading/platform_thread_linux.cc
>      "/sys/fs/cgroup";
I should change the commit title!

2024-05-13 09:14 UTC, Insun35 approved these changes
LGTM

2024-05-14 07:20 UTC, ashjeong commented on tachyon/base/threading/platform_thread_linux.cc
> +TODO(chokobole):
```
const char kCgroupDirectory[] =
     "/sys/fs/cgroup";
```
in the lines after is being put into comments and is the variable that is effectively being removed

2024-05-14 07:21 UTC, ashjeong reviewed
https://github.com/kroma-network/tachyon/pull/414/commits/41d8c41ead42fbf626f336b01f7faa25032620b2
you've missed correcting the word "sytem" to "system"

2024-05-14 07:23 UTC, TomTaehoonKim approved these changes
LGTM

2024-05-16 04:03 UTC, ashjeong approved these changes
LGTM

2024-05-16 04:46 UTC, merged