docs: update readme
kroma-network/tachyon pull request #439
Opened 2024-06-17 07:59 UTC by chokobole

# Description

This PR updates roadmap and GPU columns in README.md

2024-06-18 05:08 UTC, ashjeong commented on README.md
> +- [ ] 2024Q3 - Replace zkEVM with zkVM in [Kroma](https://kroma.network/) mainnet.
Not sure if this is a better change 🤔, but I'll leave the suggestion
```suggestion
- [ ] 2024Q3a - Implement and optimize Plonky3 in Tachyon.
- [ ] 2024Q3b - Replace zkEVM with zkVM in [Kroma](https://kroma.network/) mainnet.

2024-06-18 07:23 UTC, TomTaehoonKim commented on README.md
> +- [ ] 2024Q3 - Replace zkEVM with zkVM in [Kroma](https://kroma.network/) mainnet.
Might be too verbose, but to justify the implementation of Plonky3 in Tachyon and alignment with zkVM, how about specifying zkVM as SP1 zkVM?

2024-06-18 08:33 UTC, TomTaehoonKim approved these changes
LGTM

2024-06-18 09:03 UTC, ashjeong reviewed
LGTM

2024-06-18 09:05 UTC, ashjeong commented
Wondering on the side, but although we have Halo2 added as a Lookup should we change this to Halo2 Lookup and add Halo2 Log Derivative Lookup?

2024-06-18 09:20 UTC, chokobole commented
> Wondering on the side, but although we have Halo2 added as a Lookup should we change this to Halo2 Lookup and add Halo2 Log Derivative Lookup?

Since we don't have C api and rust binding for this, what if updating the table after this?

2024-06-19 06:49 UTC, dongchangYoo requested changes

2024-06-19 06:49 UTC, dongchangYoo commented on README.md
> +- [ ] 2024Q3b - Replace zkEVM with [SP1](https://github.com/succinctlabs/sp1) zkVM in [Kroma](https://kroma.network/) mainnet.
For convenience, how about marking it for Q2 and merging this PR after this Friday?

2024-06-20 01:41 UTC, ashjeong commented
> > Wondering on the side, but although we have Halo2 added as a Lookup should we change this to Halo2 Lookup and add Halo2 Log Derivative Lookup?
> 
> Since we don't have C api and rust binding for this, what if updating the table after this?

Sounds good~

2024-06-20 01:42 UTC, ashjeong approved these changes
LGTM

2024-06-21 06:06 UTC, dongchangYoo approved these changes
LGTM

2024-06-21 06:08 UTC, merged