feat: add rust binding for `DuplexChallenger`
kroma-network/tachyon pull request #451
Opened 2024-06-26 06:55 UTC by chokobole

# Description

This adds rust binding for `DuplexChallenger`

2024-07-03 08:21 UTC, TomTaehoonKim approved these changes
LGTM

2024-07-03 08:27 UTC, ashjeong requested changes
Instead of "for c API" in the commit titles, could you change it to "to c API"?

2024-07-03 08:27 UTC, ashjeong commented on tachyon/c/zk/air/plonky3/challenger/baby_bear_poseidon2_duplex_challenger.h
> + * @param evals A pointer to the duplex challenger structure to clone.
```suggestion
 * @param challenger A pointer to the duplex challenger structure to clone.

2024-07-03 08:27 UTC, ashjeong commented on tachyon/c/zk/air/plonky3/challenger/baby_bear_poseidon2_duplex_challenger.h
> + * @param challenger The duplex challenger to destroy.
```suggestion
 * @param challenger A pointer to the duplex challenger to destroy.

2024-07-03 08:27 UTC, ashjeong commented on tachyon/c/zk/air/plonky3/challenger/baby_bear_poseidon2_duplex_challenger_unittest.cc
> +  zk::air::plonky3::DuplexChallenger<Poseidon2, 16, 4> challenger =
```suggestion
DuplexChallenger<Poseidon2, 16, 4> challenger =

2024-07-04 01:49 UTC, ashjeong approved these changes
LGTM

2024-07-04 07:19 UTC, dongchangYoo approved these changes
LGTM

2024-07-05 01:25 UTC, merged