feat(math): implement packed field extension
kroma-network/tachyon pull request #478
Opened 2024-07-19 07:39 UTC by chokobole

# Description

This adds Extension Field of the Packed Field.

2024-07-19 08:17 UTC, ashjeong reviewed
https://github.com/kroma-network/tachyon/pull/478/commits/6e337aed6a2e590a2ff97b6efedd3cc9d9e0d53b
Please change the commit title to be: "change constexpr variables to static member variables"
Fix the typo of “refactoring” in the commit message

https://github.com/kroma-network/tachyon/pull/478/commits/5b5fcbcfb62ae018c1affc6ef227b11baf33c704
Fix the typo in the commit title : "initialization"

2024-07-19 08:23 UTC, TomTaehoonKim commented
@chokobole Is this typo or did you intend? 0453008, rerepresent -> represent.

2024-07-19 08:27 UTC, TomTaehoonKim approved these changes
LGTM. Can you add reference of `non_residue`s in the commit message body?

2024-07-19 10:33 UTC, TomTaehoonKim approved these changes
LGTM

2024-07-22 02:29 UTC, ashjeong approved these changes
LGTM

2024-07-22 04:00 UTC, batzor commented on tachyon/math/finite_fields/koala_bear/internal/BUILD.bazel
> +    base_field = "PackeKoalaBear",
```suggestion
    base_field = "PackedKoalaBear",
```

2024-07-22 04:00 UTC, batzor commented on tachyon/math/finite_fields/koala_bear/internal/BUILD.bazel
> +    class_name = "PackeKoalaBear4",
```suggestion
    class_name = "PackedKoalaBear4",
```

2024-07-22 04:02 UTC, batzor commented on tachyon/math/finite_fields/koala_bear/BUILD.bazel
> +    base_field = "PackeKoalaBear",
```suggestion
    base_field = "PackedKoalaBear",
```

2024-07-22 04:02 UTC, batzor commented on tachyon/math/finite_fields/koala_bear/BUILD.bazel
> +    class_name = "PackeKoalaBear4",
```suggestion
    class_name = "PackedKoalaBear4",
```

2024-07-22 04:56 UTC, GideokKim approved these changes
LGTM

2024-07-22 05:16 UTC, ashjeong commented
Should the `FromBasePrimeFields()` functions in quadratic, cubic, and quartic extension fields also be changed to `FromBaseFields()`?

2024-07-22 05:34 UTC, chokobole commented
> Should the `FromBasePrimeFields()` functions in quadratic, cubic, and quartic extension fields also be changed to `FromBaseFields()`?

Exactly! `GenerateInitExtField()` should also be changed, but since they are not used, so I'll just leave a comment!

2024-07-22 05:48 UTC, dongchangYoo requested changes

2024-07-22 05:48 UTC, dongchangYoo commented on tachyon/math/finite_fields/fp3.h
> +        typename FiniteFieldTraits<BasePrimeField>::PrimeField, BasePrimeField>;
How about implementing this code in FiniteFieldTraits? It appears repeatedly.

2024-07-22 09:02 UTC, batzor approved these changes
LGTM

2024-07-22 10:48 UTC, dongchangYoo approved these changes
LGTM

2024-07-22 13:56 UTC, merged