feat: enable sp1 proof generation
kroma-network/tachyon pull request #547
Opened 2024-09-23 09:27 UTC by chokobole

Description

This PR enables SP1 proof generation. All `sp1-recursion-program` unit tests have been passed, and a Fibonacci e2e test was also successful. However, the Fibonacci test currently runs 2x slower, likely due to **OPENMP** running inside **OPENMP**, which is a known issue (see #503). We need to modify the code to ensure **OPENMP** runs only once across all threads.

Key Additions

- Implemented `Hintable` traits for `DuplexChallenger` and `FriProof`.
- Implemented `Serialize` and `Deserialize` traits for `FriProof` and `ProverData`.

2024-09-24 00:42 UTC, TomTaehoonKim commented
[bde9394](https://github.com/kroma-network/tachyon/pull/547/commits/bde939457c4709e674fd68c00cd93307715f3fe0): Can you fix sp -> sp1?

2024-09-26 04:31 UTC, dongchangYoo requested changes

2024-09-26 04:31 UTC, dongchangYoo commented on tachyon/rs/base/container_util.h
> +rust::Vec<T> CreateEmptyVector(size_t size) {
How about changing the function name to `CreateDefaultVector` or `CreateInitializedVector `? That's why, the returned data might be mistakenly interpreted as a vector of length 0.

2024-09-26 06:01 UTC, dongchangYoo approved these changes
LGTM

2024-09-26 06:08 UTC, TomTaehoonKim commented
> 2401e7f

@chokobole [2401e7f](https://github.com/kroma-network/tachyon/pull/547/commits/2401e7f0a379adc7ed515be25067d327fef92c29) Can you fix sp -> sp1?

2024-09-26 08:45 UTC, batzor approved these changes
LGTM

2024-09-26 08:47 UTC, TomTaehoonKim approved these changes
LGTM

2024-09-27 05:29 UTC, merged