feat: implement quad ext field
kroma-network/tachyon pull request #62
Opened 2023-09-25 06:15 UTC by chokobole

# Description

This PR implements `QuadraticExtensionField` initially.

2023-09-25 08:37 UTC, Insun35 requested changes

2023-09-25 08:37 UTC, Insun35 commented on tachyon/math/finite_fields/quadratic_extension_field.h
> +
I think you should include the necessary headers for `std::move` and `std::ostream`
```suggestion
#include <utility>
#include <ostream>
```

2023-09-26 00:15 UTC, chokobole commented
Sorry for frequent changes during review. I've finally decided to name `Fp2` instead of `QuadraticExtensionPrimeField` like arkworks. In this manner, I'll create `Fp3`, `Fp6` and `Fp12` in the following PRs.

2023-09-26 17:57 UTC, TomTaehoonKim approved these changes
LGTM

2023-09-26 23:48 UTC, Insun35 approved these changes
LGTM

2023-09-26 23:49 UTC, merged